id: A225532D8
title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
type: translation
pechas:
- I4C2308C6
- I63A22D40
- I810053D0
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:05:14.079471
  last_modified_at: 2023-01-04 13:05:14.079476
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4C2308C6/A62F: 0F9E
  I63A22D40/B4BA: 0F9E
  I810053D0/DCD4: 0F9E
